[tool.poetry]
name = "datathon-2023"
version = "0.1.0"
description = ""
authors = ["Carlos Fernandez <carlos.ferlo@outlook.com>"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<3.13"
pandas = "^2.1.3"
langchain = "^0.0.334"
chromadb = "^0.4.17"
openai = "^1.2.3"
tiktoken = "^0.5.1"
streamlit = "^1.28.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
